# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-03-02 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='userdescription',
            field=models.CharField(default='nono', max_length=120),
        ),
    ]
